name: Continuous integration

on:
  push:
    branches-ignore:
      - "wip*"
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: "-D warnings"

jobs:
  code_checks:
    runs-on: codeberg-small
    name: Code Checks

    steps:
      - name: "Install rust-toolchain stable"
        #uses: actions-rust-lang/setup-rust-toolchain@v1
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: "Show environment"
        run: |
          rustc -vV
          cargo -vV

      - name: "Checkout"
        uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true # useful for don't rebuild cargo-readme and dependencies on fix after failure

      - name: "Cargo formatting"
        if: $${{ always() }}
        run: cargo fmt --all -- --check

      - name: "Cargo clippy"
        if: $${{ always() }}
        run: cargo clippy --profile=test --locked

      - name: "Cargo test"
        if: $${{ always() }}
        run: cargo test --locked

      - name: "Cargo doc"
        if: $${{ always() }}
        run: cargo doc --no-deps

  typos_checks:
    runs-on: codeberg-tiny
    name: Typos check
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: Check spelling of entire workspace
        uses: crate-ci/typos@master

  toml_checks:
    runs-on: codeberg-tiny
    name: Toml check
    steps:
      - uses: actions/checkout@v6

      - name: "Cargo.toml format"
        if: $${{ always() }}
        uses: gwen-lg/taplo-action@v1
        with:
          format: true
          lint: false

      - name: "Cargo.toml lint"
        if: $${{ always() }}
        uses: gwen-lg/taplo-action@v1
        with:
          format: false
          lint: true
