name: Continuous integration

on:
  push:
    branches-ignore:
      - "wip*"
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: "-D warnings"

jobs:
  ci_code_checks_and_tests:
    runs-on: ubuntu-latest
    name: Code Checks

    steps:
      - name: "Install rust-toolchain stable"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: "Show environment"
        run: |
          rustc -vV
          cargo -vV

      - name: "Checkout"
        uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true # useful for don't rebuild cargo-readme and dependencies on fix after failure

      - name: "Cargo formatting"
        if: $${{ always() }}
        run: cargo fmt --all -- --check

      - name: "Cargo clippy"
        if: $${{ always() }}
        run: cargo clippy --profile=test --locked

      - name: "Cargo test"
        if: $${{ always() }}
        run: cargo test --locked

      - name: "Cargo doc"
        if: $${{ always() }}
        run: cargo doc --no-deps


